 "use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { supabase } from "../../lib/supabase";
export default function AdminPage(){
 const [status,setStatus]=useState("Verificando sessão..."); const [email,setEmail]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const client=supabase();const {data,error}=await client.auth.getUser();if(error||!data.user){if(active){setStatus("Entre com a conta do dono para continuar.");}return;}const user=data.user;setEmail(user.email||"");const {data:profile}=await client.from("profiles").select("role,username").eq("id",user.id).maybeSingle();const owner=(user.email||"").toLowerCase()===(process.env.NEXT_PUBLIC_OWNER_EMAIL||"aetiago035@gmail.com").toLowerCase();if(active)setStatus(owner||profile?.role==="admin"?"Acesso administrativo autorizado.":"Esta conta não tem permissão de administrador.");}catch(e){if(active)setStatus(e instanceof Error?e.message:"Não foi possível verificar a conta.");}})();return()=>{active=false}},[]);
 async function logout(){await supabase().auth.signOut();window.location.href="/"}
 const allowed=status==="Acesso administrativo autorizado.";
 return <main className="admin-shell"><header className="admin-top"><Link href="/" className="brand"><span className="brand-mark">▶</span> VÍDEO<span>+</span></Link><div className="nav-actions"><Link className="btn btn-quiet" href="/">Ver site</Link><button className="btn btn-outline" onClick={logout}>Sair</button></div></header><section className="admin-content"><div className="eyebrow">CENTRAL DE CONTROLE</div><h1>Painel do <em style={{color:"var(--accent)"}}>dono.</em></h1><p className="notice">{status}</p>{allowed?<><p className="notice">Conta autenticada: <strong>{email}</strong>. Esta é a área inicial do administrador. Antes de abrir o site ao público, configure as tabelas, as regras de segurança e os recursos de publicação de vídeos.</p><div className="admin-grid"><div className="admin-tile"><span>CONTEÚDO</span><strong>Gerenciar vídeos</strong><p className="notice">Próxima etapa: moderação, publicação e remoção.</p></div><div className="admin-tile"><span>COMUNIDADE</span><strong>Usuários</strong><p className="notice">Próxima etapa: perfis, denúncias e bloqueios.</p></div><div className="admin-tile"><span>SISTEMA</span><strong>Configurações</strong><p className="notice">Acesso do dono protegido pela autenticação e pelo cargo no banco.</p></div></div></>:<div className="admin-tile" style={{marginTop:24}}><strong>Área protegida</strong><p className="notice">Faça login com o e-mail do dono. Se acabou de criar a conta, configure o projeto Supabase e execute o SQL incluído no pacote para promover a conta administrativa.</p><Link className="btn btn-primary" href="/login">Ir para login →</Link></div>}</section></main>
}